apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}-{{ .Values.deployment.env }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label }}
    spec:
      containers:
      - name: myapp
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        resources:
          limits:
            memory: {{ .Values.deployment.mem }}
            cpu: {{ .Values.deployment.cpu }}
        ports:
        - containerPort: {{ .Values.deployment.port }}

